title: CarpeQueso
email: contact@carpequeso.com
description: >-
  Reductions, morphisms, and transformations in computer science and mathematics.
baseurl: ""
url: "https://www.carpequeso.com"
lang: en_US
twitter:
  username: j_andrewcrain
  card: summary

permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: J. Andrew Crain

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

